apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJraXJpbGw0Z29vZG1vcHNhIiwicGFzc3dvcmQiOiJEZWRwZXh0bzIyODIyOSIsImF1dGgiOiJhMmx5YVd4c05HZHZiMlJ0YjNCellUcEVaV1J3WlhoMGJ6SXlPREl5T1E9PSJ9fX0=
kind: Secret
metadata:
  name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
